### ISSUE TITLE
The css file not found

### ISSUE THREAD

**Issue by tangyoulintylgit** [aalmiray/bootstrapfx#11]
WARNING: Resource "org/kordamp/bootstrapfx/bootstrapfx.css" not found.

**Comment by aalmiray** [comment]
Could you share more details on your setup and how dependencies are configured/resolved? This error occurs if the `bootstrapfx-core-0.2.4.jar` is not found in the classpath.

**Comment by tangyoulintylgit** [comment]
sorry , it`s my mistake , I do not download  the jar ,only clone your project and run the  sampler demo,
then the compiler tells me that the style file was not found.
Now it is running OK，thank you very much！
