### ISSUE TITLE
Styling ComboBox?

### ISSUE THREAD

**Issue by seinecle** [aalmiray/bootstrapfx#16]
Hi,
Thanks for this library! Would it be possible to add the styling for CombBox? It looks like this by default:

![image](https://user-images.githubusercontent.com/1244100/111743029-5b625480-8889-11eb-80d0-4dae4c34a649.png)

**Comment by HaasFynn** [comment]
There is not a certain Style for this one, but you can use the ones from btn and for Text the h1, h2, strong, etc.
