### ISSUE TITLE
Build failed, any idea on how to fix?

### ISSUE THREAD

**Issue by akkinenirajesh** [aalmiray/bootstrapfx#2]
$ gradle build
:assemble UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:bootstrapfx-core:compassCompileuri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1:in `require':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
LoadError: load error: psych -- java.lang.RuntimeException: BUG: we can not copy embedded jar to temp directory
    require at org/jruby/RubyKernel.java:937
    require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
      <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych_jars.rb:2
    require at org/jruby/RubyKernel.java:937
     (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
      <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
    require at org/jruby/RubyKernel.java:937
     (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/psych.rb:3
      <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    require at org/jruby/RubyKernel.java:937
    require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
     (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/yaml.rb:5
     (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
  load_yaml at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems.rb:624
  load_file at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/config_file.rb:328
      <top> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/config_file.rb:197
       load at org/jruby/RubyKernel.java:955
      <top> at uri:classloader:/META-INF/jruby.home/bin/gem:4
 FAILED

FAILURE: Build failed with an exception.

Also if possible can you release the compiled css file?

**Comment by mahmadmujtaba** [comment]
`It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.`

Just do it what it says here.

**Comment by efinal** [comment]
you can try the steps here. I had the same error and managed to go next step with those steps
https://plugins.gradle.org/plugin/com.jetbrains.ruby.envs/0.0.4

though I failed with another error:

Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
	[class java.lang.String, class java.lang.String]
	[class java.io.File, class java.lang.String]

have no idea on what happened
